prevent_proxy_connections: false
listeners:
- query_port: 25565
  motd: '&1MACDX2022 !!!'
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    pvp.md-5.net: pvp
  ping_passthrough: false
  priorities:
  - lobby
  bind_local_address: true
  host: 0.0.0.0:25565
  max_players: 60
  tab_size: 60
  force_default_server: true
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  default:
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
log_pings: true
connection_throttle_limit: 3
server_connect_timeout: 5000
timeout: 30000
player_limit: -1
ip_forward: true
groups:
  md_5:
  - admin
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: false
stats: 6a4362f4-e1d9-49c7-9001-7115d29a9420
online_mode: true
forge_support: false
disabled_commands:
- disabledcommandhere
servers:
  lobby:
    motd: '&aWelcome to &bMACDX2022 !'
    address: localhost:25566
    restricted: false
  CTFd1:
    motd: '&aWelcome to &bMACDX2022 !'
    address: localhost:25567
    restricted: false
  AAROC_MC_CTFD_1:
    motd: '&aWelcome to &bMACDX2022 !'
    address: 10.1.3.47:25567
    restricted: false
  AFATS_MC_CTFD_2:
    motd: '&aWelcome to &bMACDX2022 !'
    address: 10.1.3.79:25567
    restricted: false
  CAFA1_MC_CTFD_3:
    motd: '&aWelcome to &bMACDX2022 !'
    address: 10.1.3.111:25567
    restricted: false
  CAFA2_MC_CTFD_4:
    motd: '&aWelcome to &bMACDX2022 !'
    address: 10.1.3.143:25567
    restricted: false
  CCIT1_MC_CTFD_5:
    motd: '&aWelcome to &bMACDX2022 !'
    address: 10.1.3.175:25567
    restricted: false
  CCIT2_MC_CTFD_6:
    motd: '&aWelcome to &bMACDX2022 !'
    address: 10.1.3.207:25567
    restricted: false
  CMA_MC_CTFD_7:
    motd: '&aWelcome to &bMACDX2022 !'
    address: 10.1.4.47:25567
    restricted: false
  CNA_MC_CTFD_8:
    motd: '&aWelcome to &bMACDX2022 !'
    address: 10.1.4.79:25567
    restricted: false
  CPU_MC_CTFD_9:
    motd: '&aWelcome to &bMACDX2022 !'
    address: 10.1.4.111:25567
    restricted: false
  MCNDU_MC_CTFD_10:
    motd: '&aWelcome to &bMACDX2022 !'
    address: 10.1.4.143:25567
    restricted: false
